DROP TABLE IF EXISTS `#__reddesign_areas`;
DROP TABLE IF EXISTS `#__reddesign_configs`;
DROP TABLE IF EXISTS `#__reddesign_designtypes`;
DROP TABLE IF EXISTS `#__reddesign_fonts`;
DROP TABLE IF EXISTS `#__reddesign_chars`;
DROP TABLE IF EXISTS `#__reddesign_images`;
DROP TABLE IF EXISTS `#__reddesign_orders`;
DROP TABLE IF EXISTS `#__reddesign_redshops`;
DROP TABLE IF EXISTS `#__reddesign_templates`;